language: r

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    r: oldrel
  - os: linux
    dist: trusty
    sudo: required
    r: release
  - os: linux
    dist: trusty
    sudo: required
    r: devel
  - os: osx
    r: oldrel
  - os: osx
    r: release
  - os: osx
    r: devel

warnings_are_errors: true

r_packages:
  - testthat

after_success:
  - Rscript -e 'radiant.update::radiant.update()'

# install:
#  - Rscript -e "install.packages('radiant.update', repos = 'https://radiant-rstats.github.io/minicran/')"
#  - Rscript -e "install.packages('radiant.update', repos = 'https://radiant-rstats.github.io/minicran/')"
#  - Rscript -e "radiant.update::radiant.update()"
